info: |-
    Describe what this template does

demo: |-
    data <- 1:10
    clickme(heatmap, data)

scripts:
    - $shared/d3.v3.2.7.js
    - $shared/jquery.v1.8.3.min.js
    - $shared/bootstrap-tooltip.v2.3.0.js
    - $shared/d3_aux.js

styles:
    - $shared/clickme.css
    - $shared/tooltip.css

require_packages:

require_server: no


