info: |-
    A zoomable scatterplot

    Based on ideas from:
    http://bl.ocks.org/mbostock/3680957
    http://bl.ocks.org/stepheneb/1182434

original_url:

demo: |-
    clickme_points(rnorm(500),rnorm(500), color_groups = sample(letters[1:9], 500, replace = TRUE))
    clickme_points(rnorm(50),rnorm(50), color_groups = sample(letters[1:3], 50, replace = TRUE), palette = c(a="green", c = "red", b = "blue"))

scripts:
    - $shared/d3.v3.js
    - $shared/d3_aux.js
    - $shared/jquery.min.js
    - $shared/bootstrap-tooltip.v2_3.js

styles:
    - $shared/bootstrap-tooltip.css
    - $shared/clickme.css

require_packages:

require_server: no
