width: 800
height: 500
scripts:
    - d3.v2.min.js
    - nv.d3.js
    - tooltip.js
    - utils.js
    - legend.js
    - axis.js
    - scatter.js
    - line.js
    - lineWithFocusChart.js
styles:
    - nv.d3.css
