purpose: |
    Show a heatmap alongside a parallel coordinates plot.
    Each row in the heatmap is linked with a line in the line plot.
    Gene symbols appear on hover.
    The values can be separated into groups according to "cluster".

name_comments: |
    (optional) "gene_symbol" is extracted from row names of the input data if a gene_symbol column is not present.
    (optional) "cluster" is a factor used to break the rows of the input data into groups.

scripts:
    - http://html5shim.googlecode.com/svn/trunk/html5.js
    - http://code.jquery.com/jquery-1.7.1.min.js
    - http://documentcloud.github.com/underscore/underscore.js
    - http://documentcloud.github.com/backbone/backbone.js
    - http://twitter.github.com/bootstrap/assets/js/bootstrap-tooltip.js
    - http://twitter.github.com/bootstrap/assets/js/bootstrap-popover.js
    - http://mbostock.github.com/d3/d3.js
    - helper.js
    - models/longitudinal_model.js
    - views/dashboard_view.js
    - views/heatmap_view.js
    - views/pcp_view.js

styles:
    - https://fonts.googleapis.com/css?family=Lobster
    - leanback_style.css
    - longitudinal.css

require_server: true

