purpose: |
    Show a graph with directed connections. The nodes are movable.

valid_names:
    - source
    - target
    - type

name_comments: |
    "source" is the beginning of the arrow
    "target" is the end of the arrow
    "type" is the type of arrow (color)

scripts:
    - d3.min.js

styles:
    - main.css

require_packages:
    - df2json

width: 800
height: 800

original: http://bl.ocks.org/mbostock/1153292
