info: |-

original_url:

demo: |-
    clickme_lines(mat(nrow=5,ncol=5), colorize = c("a","a","b","b","a"))
    clickme_lines(mat(nrow=5,ncol=5), colorize = c("a","a","b","b","a"), interpolate = "basis")

scripts:
    - $shared/d3.v3.js
    - $shared/d3_aux.js
    - $shared/jquery.min.js
    - $shared/bootstrap-tooltip.v2_3.js

styles:
    - $shared/clickme.css
    - $shared/bootstrap-tooltip.css

require_packages:

require_server: no
